### ISSUE TITLE
Typescript and classes

### ISSUE THREAD

**Issue by ValentinAlexandrovich** [kuvshinova-am/GameOfLife#1]
Поскольку в большинстве проектов на работе ты будешь сталкиваться с typescript и классами, следует перевести проект на них.

**Comment by ValentinAlexandrovich** [comment]
Typescript не является обязательным условием, это остается на твое усмотрение) Следовательно использование интерфейсов также зависит от твоего решения использовать его в проекте или нет)

**Comment by Geksanit** [comment]
Очень ждем классов ))
