### ISSUE TITLE
js codestyle

### ISSUE THREAD

**Issue by Geksanit** [kuvshinova-am/GameOfLife#13]
не использовать инкремент
проверь по стандартам: https://rizzoma.com/topic/a87a0a28b84d6326d4f3909e8801dab7/0_b_8nel_78ian/
https://github.com/airbnb/javascript

**Comment by kuvshinova-am** [comment]
Ок, я бы сделала по другому (и пыталась), вот только тогда работать перестает. Как работать с двумерным масивом в JS без использования инкремента?

**Comment by Geksanit** [comment]
`i += 1`

**Comment by kuvshinova-am** [comment]
с итераторами разобралась.

**Comment by kuvshinova-am** [comment]
сделала

**Comment by ValentinAlexandrovich** [comment]
Это ишью не закрывай, здесь будут замечания по коду после реализации шаблонизаторов.
