### ISSUE TITLE
Подсчет соседей

### ISSUE THREAD

**Issue by ValentinAlexandrovich** [kuvshinova-am/GameOfLife#15]
https://github.com/kuvshinova-am/GameOfLife/blob/e265ee2726e2b7146c5f1deffe24f7c82d551e8e/src/js/model.js#L21
Подсчет соседей слишком захардкожен, используй для реализации имеющиеся у массивов методы.

**Comment by kuvshinova-am** [comment]
сделала

**Comment by ValentinAlexandrovich** [comment]
Можешь закрывать ишью
