### ISSUE TITLE
remove for

### ISSUE THREAD

**Issue by ValentinAlexandrovich** [kuvshinova-am/GameOfLife#16]
https://github.com/kuvshinova-am/GameOfLife/blob/7b87d40265f5cfe8176e94de5da6bef7f614cdc7/src/js/Model.js#L16

Избавиться в коде от for, используй для это методы массивов.

**Comment by kuvshinova-am** [comment]
это уже реализовано в другим ишью https://github.com/kuvshinova-am/GameOfLife/issues/13
