### ISSUE TITLE
Шаблонизаторы

### ISSUE THREAD

**Issue by ValentinAlexandrovich** [kuvshinova-am/GameOfLife#17]
Используй шаблонизаторы для создания DOM элементов во вьюхе. https://habr.com/post/219873/

**Comment by kuvshinova-am** [comment]
мне нужно какой-то конкретный шаблонизатор использовать?

**Comment by kuvshinova-am** [comment]
или ты имеешь ввиду сделать вьюху в виде pug файла? 
короче мне нужно больше информации по этому заданию. Я не понимаю что конкретно от меня требуется.

**Comment by ValentinAlexandrovich** [comment]
У тебя вьюха сейчас создается при помощи js, используй шаблонизатор для создания DOM элементов можешь выбрать любой понравившийся из статьи, к примеру Handlebars.js.

**Comment by kuvshinova-am** [comment]
готово
