### ISSUE TITLE
Замечания по именованию

### ISSUE THREAD

**Issue by chmnkh** [kuvshinova-am/GameOfLife#20]
1) this.isRun = false;
run - не та часть речи
2) updateSpeedGame
если ты хочешь сказать "скорость игры", то порядок слов в английском языке будет не прямой, а обратный: game speed. Либо speed of the game, но это тупо длиннее и меньше нас интересует.
Такая ошибка у тебя прямо много где.
3)
```
  setSizeCanvas (data) {
    this.height = data.height;
    this.width = data.width;
  }
```
почему модель знает о каких-то там канвасах?
4) checkTopCell и ему подобные: любой метод, который возвращает булин - это фактически проверка (check) чего-то, поэтому название просто checkЧто-то ни о чем не говорит.

Опять же это общие замечания которые я по модели нашел. Поэтому в других местах тебе тоже нужно будет это посмотреть.

**Comment by kuvshinova-am** [comment]
готово
