### ISSUE TITLE
Переписать countNeighbors(i, j)

### ISSUE THREAD

**Issue by chmnkh** [kuvshinova-am/GameOfLife#21]
Когда у тебя в методе количество ифов такое, что оно не помещается на экран, это явный признак того, что написано не оптимально.

**Comment by ValentinAlexandrovich** [comment]
Это было ишью, она переписала, но почему то не вмержила в ветку

**Comment by kuvshinova-am** [comment]
ага, https://github.com/kuvshinova-am/GameOfLife/commit/a0df52aa717e10b6eb2a2d28f6c18b8747c62b16 
а не вмержила потому что, посчитала что ишью №13 закроется, если это сделаю.

**Comment by kuvshinova-am** [comment]
готово
