### ISSUE TITLE
JQuery

### ISSUE THREAD

**Issue by ValentinAlexandrovich** [kuvshinova-am/GameOfLife#3]
Контроллер и модель не должны использовать jquery, у тебя для этого есть вьюха.

**Comment by kuvshinova-am** [comment]
а почему нет?
Я делала так , потому что так в [примере](http://www.wonderolie.nl/2012/javascript-mvc-a-simple-todo-list/) который был дан в описании задания.

**Comment by ValentinAlexandrovich** [comment]
Опиши здесь плиз за что должны вью, модель и контроллер.
