### ISSUE TITLE
Event Observer

### ISSUE THREAD

**Issue by ValentinAlexandrovich** [kuvshinova-am/GameOfLife#32]
https://github.com/kuvshinova-am/GameOfLife/blob/60444df13d9b94836f43cd6fc63f29ee5c866a62/src/mvc/event-observer/EventObserver.js#L14

В текущей реализации observerа возникнут ошибки при подписке на контроллер, если например у тебя имеется несколько вьюх с одинаковым именованием методов, но к примеру в одной используется этот метод, а во второй вьюхе его использование приемлемо, необходимо доработать текущую реализацию для исправления такого поведения.

**Comment by kuvshinova-am** [comment]
я не поняла что от меня требуется, объясни подробнее что ты хочешь что бы я сделала.

**Comment by ValentinAlexandrovich** [comment]
Создай в модели и вьюхе методы с одинаковым именованием test, внутри методов выведи в консоли 'это метод test Вьюхи', 'это метод test Модели' соответственно. B конструкторе контроллера вызови this.notify('test'); А теперь сама задача, нужно реализовать такой алгоритм. чтобы test Вьюхи выводил в консоль сообщение, а test Модели не вызывался. Это позволит тебе в случае подключения нескольких вьюх или моделей с одинаковым именованием методов избежать ошибок нежелательного поведения.

**Comment by kuvshinova-am** [comment]
Мне в голову приходит только один вариант.
Отправлять вместе с данными, информацию о получателе, и в обсервере ее обрабатывать. 
Но мне кажется что это плохой вариант.

**Comment by ValentinAlexandrovich** [comment]
В можно оправлять тип отправителя вместе с данными, а в получателе проверять числится ли этот в отправителях и какие методы ему доступны. Посредством обсервера обрабатывать эту инфу и в случае совпадения, запускать метод с данными, иначе игнорить вызов notify для класса получателя.

**Comment by ValentinAlexandrovich** [comment]
При создании архитектуры следует учесть, что проверку для получателя лучше реализовать в отдельном классе, от которого будет наследоваться класс EventObserver и вызывать метод проверки на допустимость вызова метода обсервера в notify. Также предусмотреть автоматическое определение отправителя в EventObserver, как вариант можно воспользоваться таким примером архитектуры.
![xasx](https://user-images.githubusercontent.com/31854808/47277432-b4f7c380-d5ea-11e8-9db8-701b559cf7d4.jpg)

**Comment by ValentinAlexandrovich** [comment]
При создании архитектуры следует учесть, что проверку для наблюдателя лучше реализовать в отдельном классе, от которого будет наследоваться класс EventObserver и вызывать метод проверки на допустимость вызова метода обсервера в notify. Также предусмотреть автоматическое определение отправителя в EventObserver, как вариант можно воспользоваться таким примером архитектуры.
![xasx](https://user-images.githubusercontent.com/31854808/47277506-36e7ec80-d5eb-11e8-87f9-6589b6e02a6b.jpg)

**Comment by ValentinAlexandrovich** [comment]
При создании архитектуры следует учесть, что проверку для наблюдателя лучше реализовать в отдельном классе, от которого будет наследоваться класс EventObserver и вызывать метод проверки на допустимость вызова метода обсервера в notify. Также предусмотреть автоматическое определение отправителя в EventObserver, как вариант можно воспользоваться таким примером архитектуры.
![xasx](https://user-images.githubusercontent.com/31854808/47278410-01df9800-d5f3-11e8-9c5a-3cc5acf073b9.jpg)

**Comment by ValentinAlexandrovich** [comment]
a

**Comment by kuvshinova-am** [comment]
**Можно оправлять тип отправителя вместе с данными**
Это я сделала вот так:
![2018-10-23 5 16 44](https://user-images.githubusercontent.com/24365265/47353869-73990e00-d6e7-11e8-8644-89fb447ab274.png)
А вот что дальше делать я не понимаю. 
Эта часть для меня вообще не понятна:
**а в получателе проверять числится ли он в отправителях**

**Comment by ValentinAlexandrovich** [comment]
Зачем пересылать лишние данные? В моем примере есть уже еммитер этого вполне достаточно для проверки. К примеру ты можешь создать класс Checkers и отнаследовать от него  EventObserver. В классе Checkers можно создать массив объектов. К примеру такой: => 

 this.allEvents = [
      {
        View: [{
          Controller: [имена методов доступные для notify контроллером],
        }],
        Model: [{
          Controller: [имена методов доступные для notify контроллером],
        }],
        Controller: [{
          View: [имена методов доступные для notify вьюхой],
          Model: [имена методов доступные для notify моделью],
        }],
      },
    ];
При notify пробегаться по allEvents, находить по еммитру нужный массив с именем получателя и доступными для него методами, и проверять имеется ли имя в списке имен методов. Если нет то в notify игноришь код который вызывает метод наблюдателя.

**Comment by ValentinAlexandrovich** [comment]
Я там коммент в мердже оставил, подправь плиз чтобы лучше смотрелось и можешь мержить)

**Comment by kuvshinova-am** [comment]
я по этому ишью в пулл реквесте  не вижу комментариев.
