### ISSUE TITLE
Замечания по модели

### ISSUE THREAD

**Issue by chmnkh** [kuvshinova-am/GameOfLife#34]
1. Конструктор
есть в конструкторе такие строчки:
```
    this.matrix = [];
    this.pastMatrixStates = [];
```

при этом есть метод initMatrix, которые вызывается в конструкторе и в котором есть такие строчки:
```
this.matrix = Array.from({ length: width }, () => Array.from({ length: height }, () => constants.DEAD_CELL));
this.pastMatrixStates = [];
```
получается инициализация этих полей в конструкторе избыточная.
Еще есть инициализация таймера пустым объектом, что во-первых странно (это же таймер), а во-вторых вообще не понять зачем сделано.
2. #33 проблемы из этого ишью. После того как его сделаешь, посмотришь, что надо исправить.
3. updateMatrix():  ```this.isMatrixRepeated() ? this.notify('endGame') : 0;``` что за 0 ?) не надо тернарниками увлекаться прямо, если у тебя только для if'a условие нужно, так и пиши иф, эта штука с 0 выглядит ну прямо не очень. Опять же странно, что у тебя  после конца игры еще матрица каким-то образом обновиться может (я говорю о том, что отрабатывают еще 2 строчки кода после этого тернарника в любом случае), но тут поясни, если я не прав.
4. isMatrixRepeated(): 
```result ? this.pastMatrixStates = [] : this.pastMatrixStates.push(this.matrix);```  опять же о тернарниках: тернарник - это конструкция, которая в зависимости от условия перед знаком "?" вернет одно из двух значений, до : или после. Просто так тернарник сам по себе смысла не имеет, ибо служит именно _для получения значения в зависимости от условия_. То, что ты тернарники пишешь там, где по идее должны быть обычные иф-элсы это неправильно и запутанно. То, что у тебя, если result кастанется в true, pastMatrixStates присвоится пустой массив, это скорее какой-то побочный эффект работы тернарника, а не то, зачем тернарники на самом деле используются. Это все хоть и работает, но код становится очень неочевидным и запутанным.
5. getNextMatrixState()
метод получения следующего состояния матрицы возвращает 0 или 1, что-то не так с именованием?
6.  getNextMatrixState(row, column)
сложно условия читаются, попробуй тут порефакторить, порасставлять If/else'ы грамотно, чтобы логика более четко прослеживалась
7. getCountAliveNeighbours(row, column, matrix)
кажется лишним передача третьего аргумента, ибо вычисления происходят в рамках модели, и она может матрицу сразу брать из this?

**Comment by kuvshinova-am** [comment]
готово

**Comment by ValentinAlexandrovich** [comment]
Внес в самом конце пуллреквеста свои замечанию по поводу spread оператора и т.д. Внеси плиз соответсвующие измы перед мерджом.

**Comment by kuvshinova-am** [comment]
готово

**Comment by ValentinAlexandrovich** [comment]
Оставил комментарии в пулл реквест

**Comment by ValentinAlexandrovich** [comment]
оставил комментарии

**Comment by kuvshinova-am** [comment]
исправила
