### ISSUE TITLE
Замечания по view

### ISSUE THREAD

**Issue by chmnkh** [kuvshinova-am/GameOfLife#37]
1) Лучше как сказано в стандартах, добавлять все-таки префиксы $ к имени переменных (свойств в данном случае), содержащих JQuery Object, чтобы по коду было явно видно всегда, с чем мы имеем дело.
```
    this.widthInput = $('.js-width-form__input');
    this.heightInput = $('.js-height-form__input');
    ...
```
2) this.widthInput.on('blur', () => {
      this.notify('changeCanvasSize', { width: this.widthInput.val(), height: this.heightInput.val() });
    });
Все обработчики нужно в отдельные методы вынести. Посмотри [здесь](https://rizzoma.com/topic/a87a0a28b84d6326d4f3909e8801dab7/0_b_8nel_8av0m/) в п.3 как это правильно сделать.
Кода будешь их выносить, тебе придется биндить контекст. Чтобы это красиво сделать (а не руками писать все бинды) можешь погуглить какие-нибудь bind-декораторы и заюзать.
3) data - про переменые с именем data я писал в замечаниях к пулл реквесту по модели
4) updateField():
```
    Array.from(
      { length: data.width }, (row, i) => Array.from(
        { length: data.height }, (col, j) => (data.matrix[i][j]
          ? c.fillRect(i * this.cellSize, j * this.cellSize, this.cellSize, this.cellSize)
          : 0),
      ),
    );
```
тут разберись, что ты хотела написать, потому что сейчас написано так, что у тебя с помощью Array.from создается матрица, которая просто вникуда вываливается (т.е. создается и никуда не записывается), а в процессе создания матрицы как какой-то побочный эффект канвас отрисовывает что-то иногда. Тут можно все более явно и очевидно написать.

**Comment by kuvshinova-am** [comment]
**тут разберись, что ты хотела написать**
Я знаю что тут я хотела написать.
Здесь происходит обход массива, и если ячейка равна 1 то происходит от рисовка ячейки на канвасе. 
**Тут можно все более явно и очевидно написать.**
Ну тогда объяснение в студию пожалуйста, потому что я не знаю как это сделать более явно и очевидно.

**Comment by chmnkh** [comment]
> Здесь происходит обход массива, и если ячейка равна 1 то происходит от рисовка ячейки на канвасе.

у тебя происходит не обход массива, у тебя происходит создание двумерного массива, который потом никуда не записывается, а побочным эффектом создания этого двумерного массива является проверка матрицы, в результате которой у тебя канвас отрисовывается

> Ну тогда объяснение в студию пожалуйста, потому что я не знаю как это сделать более явно и очевидно

как в джаваскрипте массивы обойти - стандартная задача, и в вопросах на собес даже есть, какие тут сложности-то могут быть? проблема твоего кода в том, что вместо того, чтобы обходить массив, с которым ты работаешь, ты зачем-то создаешь новый, а в процессе создания что-то там проверяешь, зачем таки обходные пути?

**Comment by kuvshinova-am** [comment]
готово

**Comment by kuvshinova-am** [comment]
опять пулреквест закрылся из-за другого. если нужны будут еще изменения по этому ишью, сделаю новый пр.

**Comment by chmnkh** [comment]
2 замечания:
1) 2 пункт: ты не совсем то сделала, ты вынесла бинды событий в отдельные методы. А имелось в виду, что _обработчики_ _событий_ в отдельные методы вынести. Т.е. чтобы было не так:
```
this.$canvas.on('click', (event) => {
      const x = (event.offsetX / this.cellSize) < 0
        ? Math.round(event.offsetX / this.cellSize)
        : Math.floor(event.offsetX / this.cellSize);
      const y = (event.offsetY / this.cellSize) < 0
        ? Math.round(event.offsetY / this.cellSize)
        : Math.floor(event.offsetY / this.cellSize);
      this.notify('сhangeСellStatus', { x, y });
    });
```
а так:
```
this.$canvas.on('click', this.handleCanvasClick);
```
а бинд всех слушателей как раз в одном методе типа initEventListeners норм смотрится.

**Comment by kuvshinova-am** [comment]
готово

**Comment by kuvshinova-am** [comment]
сделала
