### ISSUE TITLE
Игра не работает

### ISSUE THREAD

**Issue by ValentinAlexandrovich** [kuvshinova-am/GameOfLife#44]
![peek 2018-11-03 08-47](https://user-images.githubusercontent.com/31854808/47946904-1a31aa00-df45-11e8-9372-f847694e5d07.gif)

**Comment by kuvshinova-am** [comment]
я не смогла нормально смержить ветки. были конфликты которые я долго пыталась разрешить, были проблемы с версиями babel модулей. то что сейчас в мастере не возможно сделать билд появляется ошибка
![2018-11-13 5 06 20](https://user-images.githubusercontent.com/24365265/48406326-c1dd8200-e766-11e8-8d55-49d582e4364c.png)
но из локалхоста работает. Моих сил уже нет что бы самостоятельно решить эти проблемы.

**Comment by ValentinAlexandrovich** [comment]
А если не мержить а просто перенести код в мастер? Возможно не обновила node_modules.

**Comment by kuvshinova-am** [comment]
я уже смержила. и когда разрешила конфликты посыпались ошибки одна за одной, все связанные с babel пришлось искать подходящую комбинацию для того что бы хотя бы на локал хост запустилось. теперь ошибка из-за UglifyJsPlugin, без него все билдиться, но остается та ошибка из-за которой его и добавили.

**Comment by kuvshinova-am** [comment]
я буквально сотни раз удаляла всю папку node_modules и все устанавливала по новой.

**Comment by chmnkh** [comment]
1) Проблема появилась именно после мержа?
Если так, то:
2) Ты пыталась откатывать ветку на состояние ДО мержа? работало ли тогда?
3) Работает ли ветка, которая мержилась?

**Comment by kuvshinova-am** [comment]
> Проблема  появилась именно после мержа?

да

> Работает ли ветка, которая мержилась?

работает

> Ты пыталась откатывать ветку на состояние ДО мержа? работало ли тогда?

если речь о master то была ошибка при нажатии на канвас, которую мы собственно и пытаемся решить новыми изменениями.

**Comment by ValentinAlexandrovich** [comment]
![peek 2018-11-15 23-32](https://user-images.githubusercontent.com/31854808/48567182-0b78c900-e92f-11e8-8500-da1a7d4e4fbe.gif)

**Comment by ValentinAlexandrovich** [comment]
Такие проблемы будут встречаться в программировании сплошь и рядом, нужно учится решать их самой.
