### ISSUE TITLE
Архитектура

### ISSUE THREAD

**Issue by ValentinAlexandrovich** [kuvshinova-am/GameOfLife#5]
У тебя сейчас очень сильно завязанны model, view, controller, что будет если мы захотим прикрепить еще одну вьюху, для тестинга, либо бизнес логику, которая будет расчитывать выплаты игрокам в случае побед. Реализуй паттерн наблюдатель для снижения взаимосвязи, пусть у каждого обьекта будет метод сабскрайб, в котрый будет передаваться обьект（во вьюху контроллер, в контроллер модель и вьюха, к модель контроллер) с публичными методами. Для определения типов передаваемых обьектов используй интерфейсы. Доступ к внутренним переменным должен осуществляться посредством публичных методов.

**Comment by ValentinAlexandrovich** [comment]
Использование интерфейсов зависит от твоего решения, захочешь или нет ты применять typescript в своем проекте)

**Comment by kuvshinova-am** [comment]
я не понимаю почему у меня сильно завязанны model, view, controller.
Помойму все реализованно через слушателей.
т.е. во view навешанны слушатели например вот так
![screenshot from 2018-09-14 16-01-50](https://user-images.githubusercontent.com/24365265/45540808-95c18580-b837-11e8-8674-b9282caa20af.png)
модель генерирует события, которые она отправляет в боди вот так:
![screenshot from 2018-09-14 16-03-50](https://user-images.githubusercontent.com/24365265/45540939-e2a55c00-b837-11e8-8ccf-d87a63a4a6f9.png)
контроллер ловит эти события и взаимодействует с виью и моеделью. 
![screenshot from 2018-09-14 16-05-30](https://user-images.githubusercontent.com/24365265/45541015-12546400-b838-11e8-886d-b2d0327fcf53.png)
и данная структура сделанна на базе хорошего [примера](http://www.wonderolie.nl/2012/javascript-mvc-a-simple-todo-list/) из задания.

**Comment by ValentinAlexandrovich** [comment]
Без модели и вью, не инициализируешь контроллер. А если мы захотим прикрутить к контроллеру несколько вьюх несвязанных между собой с одинаковыми методами? Контроллеру, как и модели нет необходимости что либо знать о DOM, а если к примеру у нас не будет DOMа (захотим прикрутить консольную версию вьюхи).

**Comment by kuvshinova-am** [comment]
внесла изменения

**Comment by ValentinAlexandrovich** [comment]
Отписался внутри коммита)

**Comment by kuvshinova-am** [comment]
надеюсь это оно )))

**Comment by ValentinAlexandrovich** [comment]
Можно мержить)
