### ISSUE TITLE
БЭМ

### ISSUE THREAD

**Issue by ValentinAlexandrovich** [kuvshinova-am/GameOfLife#6]
Откорректировать согласно первому и второму макету

**Comment by kuvshinova-am** [comment]
У меня тут вопрос. Я когда смержила ветку с архитектурой у меня автоматом закрылись ишью 1,2,3,4 и 5. Я не знаю по ним еще нужно ждать комментарии или нет. Во этому открыла их заново, но пулреквесты по ним уже вернуть не могу. Что ответа что с ними делать. Вроде бы я по ним все сделала как было нужно.

**Comment by ValentinAlexandrovich** [comment]
Пока оставь так открытым. Я посмотрю это ишью в конце после окончательной реализации методов классов, если все будет ок, то закроем его.

**Comment by ValentinAlexandrovich** [comment]
1) page-container - неудачное название  блока. Возможно лучше подойдет просто game. 
2) page-container__canvas также. Куда лучше подойдет game__field.
3) control-elements-container - почему это блок ты его переиспользуешь где то? Тут лучше убрать section и вместо нее использовать form c классом game__dashboard.
4) Для чего ты каждую кнопку, инпут оборачиваешь в форму? Убрать лишние формы.
5) Элементы панели управления лучше назвать по типу game__dashboard-control_assigment_start и т.д,

**Comment by ValentinAlexandrovich** [comment]
Посмотри плиз еще вот это ишью https://github.com/kuvshinova-am/GameOfLife/pull/38#pullrequestreview-169597174 оно в верстке, исправь его плиз тоже заодно- чтобы новое ишью не создавать

**Comment by ValentinAlexandrovich** [comment]
Создай ветку, и выложи тут чтобы можно было глянуть код.

**Comment by kuvshinova-am** [comment]
выложила

**Comment by kuvshinova-am** [comment]
У меня тут вопросы:
почему в пункте 3. - game__dashboard, а в пункте 5 уже **game__dashboard-control**_assignment_start.
Для чего добавился control? разве не должно быть в обоих местах одинаково? 
И я так понимаю что этот варианта game__dashboard-control_assignment_start подходит для кнопок, вот так:
game__dashboard-control_assignment_new-game
game__dashboard-control_assignment_start
game__dashboard-control_assignment_pause
А вот с инпутами другая проблема там есть лэйблы, и так уже не получиться. 
И вообще что мне теперь делать, пока у меня кнопки и лэйблы были внутри форм, все нормально отображалось, теперь все поехало, и как нормально сделать позиционирование без дополнительного вложения в другой тэг я не понимаю.

**Comment by ValentinAlexandrovich** [comment]
Нет, это разные вещи. Dashboard - панель управления(включает в себя все элементы), а dashboard-control элемент управления панели. Именования не являются обязательными возможно ты подберешь более удачное именование или иерархию. Dashboard  это и есть твоя обертка, которую ты можешь использовать для позиционирования. А в чем состоит проблема именования с лейблами?

**Comment by kuvshinova-am** [comment]
внесла изменения https://github.com/kuvshinova-am/GameOfLife/pull/46

**Comment by kuvshinova-am** [comment]
сделала

**Comment by ValentinAlexandrovich** [comment]
Оставил коммент по поводу error

**Comment by ValentinAlexandrovich** [comment]
![peek 2018-11-13 14-32](https://user-images.githubusercontent.com/31854808/48398054-4d98e380-e752-11e8-8548-5be0839cc70e.gif)
Думаю это поможет решить твою проблему с ошибками при билд сборке) Доправляй и мержи. Как GH Pages заработают, закрывай это ишью https://github.com/kuvshinova-am/GameOfLife/issues/44
