### ISSUE TITLE
Не реализованы правила останова игры

### ISSUE THREAD

**Issue by ValentinAlexandrovich** [kuvshinova-am/GameOfLife#7]
Игра прекращается, если: 
=> на поле не останется ни одной «живой» клетки (если создать клетку на поле после исчезновения в процессе игры всех клеток, видно что игра не останавливается, а продолжается).
=> конфигурация на очередном шаге в точности (без сдвигов и поворотов) повторит себя же на одном из более ранних шагов (складывается периодическая конфигурация) 
при очередном шаге ни одна из клеток не меняет своего состояния (складывается стабильная 
=> конфигурация; предыдущее правило, вырожденное до одного шага назад)

**Comment by kuvshinova-am** [comment]
напиши пожайлуста название тех методов которые сравнивают массивы, по который ты говорил.

**Comment by ValentinAlexandrovich** [comment]
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array
Здесь подробно описаны имеющиеся методы массивов, реализация зависит от твоего вкуса)

**Comment by ValentinAlexandrovich** [comment]
https://learn.javascript.ru/array-iteration здесь собрана выжимка из методов, которых досточно для реализации твоей задачи)

**Comment by kuvshinova-am** [comment]
сделала

**Comment by ValentinAlexandrovich** [comment]
Можешь закрывать.
